apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contracts-service
  name: contracts-service
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contracts-service
  template:
    metadata:
      labels:
        app: contracts-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/contracts-service:__COMMIT_HASH__
          imagePullPolicy: Always
          name: contracts-service
          env:
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db
                  key: mongodb-root-password
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contracts-service
  name: contracts-service
  namespace: __NAMESPACE__
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: contracts-service
  type: ClusterIP
